/*

 ShareVol
 Lightweight WebGL volume viewer/slicer

 Copyright (c) 2014, Monash University. All rights reserved.
 Author: Owen Kaluza - owen.kaluza ( at ) monash.edu

 Licensed under the GNU Lesser General Public License
 https://www.gnu.org/licenses/lgpl.html

*/
var $j=jQuery.noConflict(),SERVER="http://"+window.location.host,TOTAL_SCREENS=0,N_NODES=0,N_PER_NODE=0,NODES,BEFORESORT=[],STATUS=0;NODES=[];var SELECTED_STAMPS=[],TOGGLE_VIZ=1,WORKFLOW_FILE="",SAVE_WORKFLOW=0,MINICAVE,HISTORY_DATA,APP_TYPE="",DATA;
$j(function(){DATA=json_data;var a=function(a){this._data=DATA;this._data.sort(function(a,b){return parseFloat(a.Subject_ID)-parseFloat(b.Subject_ID)});this._init()};a.prototype={_init:function(){var b=this;this._screensUl=$j("#screensUl");this._choicesUl=$j("#choicesUl");this._getHistogram=$j("#getHistogram");$j("#screensUl").resizable({aspectRatio:3.84});$j("#divHistory").hide();$j("#divTag").hide();$j("#divMoment").hide();$j("#toggle_history_request").change(function(){"visualisation"==$j("#toggle_history_request").val()&&
($j("#divSVG").show(),$j("#divMoment").hide(),$j("#divHistory").hide(),$j("#divTag").hide());"moment"==$j("#toggle_history_request").val()&&($j("#divSVG").hide(),$j("#divMoment").show(),$j("#divHistory").hide(),$j("#divTag").hide());"history"==$j("#toggle_history_request").val()&&($j("#divSVG").hide(),$j("#divMoment").hide(),$j("#divHistory").show(),$j("#divTag").hide());"tags"==$j("#toggle_history_request").val()&&($j("#divSVG").hide(),$j("#divMoment").hide(),$j("#divHistory").hide(),$j("#divTag").show())});
this._createPanels();$j("#stopEncubePR").click(function(){if(confirm("Are you sure you want to stop encube-PR?")){var a=[];a.push({node:$j(".ui-selected").attr("node"),panel:$j(".ui-selected").attr("panelScreenNumber")});$j.ajax({type:"POST",url:SERVER+"/update",data:"stopEncubePR="+encodeURIComponent(JSON.stringify(a))});$j("startstopEncubePR").text="Start encube-PR";$j("startstopEncubePR").attr("Action","Start")}});$j("#request_from_host").change(function(){if("ntracks"==$j("#request_from_host").val()){var b=
[];b.push({dummy:"data"});console.log("In ntracks");var d=(new Date).getTime();$j.ajax({type:"POST",url:SERVER+"/update",data:"ntracks="+encodeURIComponent(JSON.stringify(b)),success:function(b){var c=(new Date).getTime()-d;console.log("Query ntracks -- request time (ms): "+c);a.prototype._ntracks(b)}})}"histogram"==$j("#request_from_host").val()&&(console.log("In histogram"),1==$j(".ui-selected, .ui-selecting").length?"-1"!=$j(".ui-selected").attr("Subject_ID")&&(b=[],b.push({node:$j(".ui-selected").attr("node"),
panel:$j(".ui-selected").attr("panelScreenNumber")}),d=(new Date).getTime(),$j.ajax({type:"POST",url:SERVER+"/update",data:"histogram="+encodeURIComponent(JSON.stringify(b)),success:function(b){var c=(new Date).getTime()-d;console.log("Query histogram -- request time (ms): "+c);a.prototype._histogram(b,"histogram")}})):alert("To request an histogram, select one screen, and one screen only."));"area"==$j("#request_from_host").val()&&(console.log("In histogram"),1==$j(".ui-selected, .ui-selecting").length?
"-1"!=$j(".ui-selected").attr("Subject_ID")&&(b=[],b.push({node:$j(".ui-selected").attr("node"),panel:$j(".ui-selected").attr("panelScreenNumber")}),$j.ajax({type:"POST",url:SERVER+"/update",data:"histogram="+encodeURIComponent(JSON.stringify(b)),success:function(b){a.prototype._histogram(b,"area")}})):alert("To request an histogram, select one screen, and one screen only."));"moment"==$j("#request_from_host").val()&&(console.log("In moment"),1==$j(".ui-selected, .ui-selecting").length?"-1"!=$j(".ui-selected").attr("Subject_ID")&&
(b=[],b.push({node:$j(".ui-selected").attr("node"),panel:$j(".ui-selected").attr("panelScreenNumber")}),$j.ajax({type:"POST",url:SERVER+"/update",data:"moment="+encodeURIComponent(JSON.stringify(b)),success:function(b){a.prototype._moment(b,"moment")}})):alert("To request an histogram, select one screen, and one screen only."))});$j("#swap").click(function(){2==$j(".ui-selected").length?(b._swap(SELECTED_STAMPS),$j("#screensUl .ui-selected").effect("shake",{distance:3})):alert("You need to select 2 screens before swaping.")});
$j("#snapshot").click(function(){console.log("In snapshot");html2canvas(document.body,{onrendered:function(a){$j("#divSVG").appendChild('<div class="scroll-content-item ui-widget-header">'+a+"</div>");console.log(a)}})});$j("#unloadSelected").click(function(){b._unload(SELECTED_STAMPS);$j("#screensUl .ui-selected").effect("shake",{distance:3}).removeClass("ui-selected");SELECTED_STAMPS=[];var a=0;$j("#screensUl").find("li").each(function(){BEFORESORT[a]=$j(this).attr("Subject_ID");a++})});$j("#loadChecked").click(function(){var b=
0;$j(".choices").find("tr").each(function(){if(b<TOTAL_SCREENS){var d=$j(this);if(d.find('input[type="checkbox"]').is(":checked")){d=d.find(".td_subject_id").text();$j("#screens-li-"+b).attr("Subject_ID",d);$j("#screens-li-"+b).html("<div class='handle'><span class='ui-icon ui-icon-carat-2-n-s'></span></div>"+d);var e=$j("#screens-li-"+b).hasClass("ui-selected")?"1":"0",f=[];f.push({node:$j("#screens-li-"+b).attr("node"),panel:$j("#screens-li-"+b).attr("panelScreenNumber"),id:d,selected:e});console.log("");
console.log("node",$j("#screens-li-"+b).attr("node"));console.log("panel",$j("#screens-li-"+b).attr("panelScreenNumber"));console.log("id",d);console.log("selected",e);console.log("");$j.ajax({type:"POST",url:SERVER+"/update",data:"loadOne="+encodeURIComponent(JSON.stringify(f))});1==SAVE_WORKFLOW&&a.prototype._createWorkflowHistory();b++}}})});this._screensUl.sortable({revert:!0,handle:".handle",stop:function(){b._updateNodes();b._reorder()}});this._screensUl.bind("mousedown",function(a){a.metaKey=
!0}).selectable({filter:"li",cancel:".handle",selecting:function(a,b){},selected:function(b,d){console.log($j(d.selected).attr("id"));console.log(SELECTED_STAMPS);var e=SELECTED_STAMPS.indexOf($j(d.selected).attr("id"));-1<e?(console.log($j(d.selected).attr("id")+" is selected."),SELECTED_STAMPS.splice(e,1),$j(d.selecting).prop("selected",!1),e="0"):(console.log($j(d.selected).attr("id")+" is not selected."),SELECTED_STAMPS.push($j(d.selected).attr("id")),e="1");var f=[];f.push({node:$j(d.selected).attr("node"),
panel:$j(d.selected).attr("panelScreenNumber"),selected:e});$j.ajax({type:"POST",url:SERVER+"/update",data:"update_selected="+encodeURIComponent(JSON.stringify(f))});1==SAVE_WORKFLOW&&a.prototype._createWorkflowHistory()},unselecting:function(b,d){console.log("unselecting: "+$j(d.unselecting).attr("id"));var e=SELECTED_STAMPS.indexOf($j(d.unselecting).attr("id"));-1<e&&SELECTED_STAMPS.splice(e,1);e=[];e.push({node:$j(d.unselecting).attr("node"),panel:$j(d.unselecting).attr("panelScreenNumber"),selected:"0"});
$j.ajax({type:"POST",url:SERVER+"/update",data:"update_selected="+encodeURIComponent(JSON.stringify(e))});1==SAVE_WORKFLOW&&a.prototype._createWorkflowHistory()},unselected:function(a,b){$j(".ui-selected")}})},_histogram:function(b,c){"string"===typeof b&&(b=jQuery.parseJSON(b));for(var d="Node: "+b.node+", Panel:"+b.panel,e=b.nbins,f=b.dmin,g=b.dmax,k=b.incr,n=[],h={},l=0;l<b.data.length;l++){var m=b.data[l].bin,m=m>g?g:m,q=b.data[l].count;void 0===h[m]&&(h[m]=0);h[m]+=q}for(var p in h)n.push({x:p,
y:h[p]});"histogram"==c?createHistogram(n,e,f,g,k,d,b.node,b.panel,b.mean,b.stand_dev,b.min_filter,b.max_filter):linked_areas(d,b.node,b.panel,b.mean,b.stand_dev,b.min_filter,b.max_filter);1==SAVE_WORKFLOW&&a.prototype._createWorkflowHistory()},_moment:function(a,c){},_ntracks:function(b){"string"===typeof b&&(b=jQuery.parseJSON(b));console.log(b);createScatterTracks(b.labels,b.colours);1==SAVE_WORKFLOW&&a.prototype._createWorkflowHistory()},_swap:function(b){$j("#"+b[0]).attr("id","tempId0");$j("#"+
b[1]).attr("id","tempId1");$j("#tempId0").attr("id",b[1]);$j("#tempId1").attr("id",b[0]);var c=$j("#"+b[0]).attr("Subject_ID");$j("#"+b[0]).attr("Subject_ID",$j("#"+b[1]).attr("Subject_ID"));$j("#"+b[1]).attr("Subject_ID",c);c=document.getElementById(b[0]).innerHTML;document.getElementById(b[0]).innerHTML=document.getElementById(b[1]).innerHTML;document.getElementById(b[1]).innerHTML=c;c=[];c.push({node:$j("#"+b[0]).attr("node"),panel:$j("#"+b[0]).attr("panelScreenNumber"),id:$j("#"+b[0]).attr("Subject_ID"),
selected:"1"});c.push({node:$j("#"+b[1]).attr("node"),panel:$j("#"+b[1]).attr("panelScreenNumber"),id:$j("#"+b[1]).attr("Subject_ID"),selected:"1"});$j.ajax({type:"POST",url:SERVER+"/update",data:"reorder="+encodeURIComponent(JSON.stringify(c))});1==SAVE_WORKFLOW&&a.prototype._createWorkflowHistory();b=$j("#screensUl").sortable("toArray",{attribute:"Subject_ID"});for(i=0;i<b.length;i++)BEFORESORT[i]=b[i]},_unload:function(b){for(var c=[],d=0;d<b.length;d++)$j("#"+b[d]).attr("Subject_ID","-1"),document.getElementById(b[d]).innerHTML=
"<div class='handle'><span class='ui-icon ui-icon-carat-2-n-s'></span></div>",c.push({node:$j("#"+b[d]).attr("node"),panel:$j("#"+b[d]).attr("panelScreenNumber"),id:$j("#"+b[d]).attr("Subject_ID"),selected:"0"});$j.ajax({type:"POST",url:SERVER+"/update",data:"reorder="+encodeURIComponent(JSON.stringify(c))});1==SAVE_WORKFLOW&&a.prototype._createWorkflowHistory()},_reorder:function(){var b=this._screensUl.sortable("toArray"),c=this._screensUl.sortable("toArray",{attribute:"Subject_ID"});data=[];for(var d=
-1,e=-1,f=[],g=0;g<c.length;g++){var k=$j("#"+b[g]).hasClass("ui-selected")?"1":"0";if(-1==d)BEFORESORT[g]!=c[g]&&(-1==d&&(d=1),f.push({node:$j("#"+b[g]).attr("node"),panel:$j("#"+b[g]).attr("panelScreenNumber"),id:$j("#"+b[g]).attr("Subject_ID"),selected:k}));else if(-1==e)BEFORESORT[g]!=c[g]?f.push({node:$j("#"+b[g]).attr("node"),panel:$j("#"+b[g]).attr("panelScreenNumber"),id:$j("#"+b[g]).attr("Subject_ID"),selected:k}):e=1;else break}0!=f.length&&($j.ajax({type:"POST",url:SERVER+"/update",data:"reorder="+
encodeURIComponent(JSON.stringify(f))}),1==SAVE_WORKFLOW&&a.prototype._createWorkflowHistory());for(g=0;g<c.length;g++)BEFORESORT[g]=c[g]},_updateNodes:function(){var a=0,c=0;$j("ul.screens li").each(function(d){$j(this).attr("node",NODES[a].node_id);$j(this).attr("panelScreenNumber",NODES[a].panels[c].panel_id);$j(this).attr("id","screens-li-"+d);(d+1)%N_PER_NODE||(a+=1);c=(d+1)%N_PER_NODE?c+1:0})},_createChoices:function(){var a=[];a.push(this._createHeader(Object.keys(DATA[0])));$j("#thHead").html(a.join(""));
for(var a=[],c=0;c<DATA.length;c++)a.push(this._createList(DATA[c],c));$j("#choicesTableBody").html(a.join(""));$j("#choicesTable").tablesorter({headers:{0:{sorter:!1}}})},_createHeader:function(a,c){var d='<th class="th_checkbox"><input type="checkbox" id="selectAll" /></th>';for(c=0;c<a.length;c++)COLUMNS_TO_IGNORE.includes(c)||(d+='<th class="th_sortable th_'+a[c]+'">'+a[c]+"</th>");return d},_createList:function(a,c){var d;d='<tr class="tr_body" id="table_line_'+c+'">'+('<td class="td_checkbox"><input type="checkbox" class="inputChkbox" id="chkbox_'+
c+'" /></td>');console.log("panel: "+a);for(var e="",f=0;f<Object.keys(a).length;f++)COLUMNS_TO_IGNORE.includes(f)||(e=Object.keys(a)[f],d+='<td class="td_'+e.toLowerCase(e)+' td_sortable">'+a[e]+"</td>");return d+="</tr>"},_createWorkflowHistory:function(){$j.getJSON(WORKFLOW_FILE,function(b){HISTORY_DATA=b;for(var c=[],d=b.last_id-1;0<=d;d--)c.push(a.prototype._createHistoryList(b.records[d],d));$j("#historyTableBody").html(c.join(""))})},_createHistoryList:function(a,c){var d;d='<tr class="tr_body" id="table_line_'+
c+'">'+('<td class="td_history_id td_sortable">'+c+"</td>");d+='<td class="td_history_event td_sortable">'+a.descriptor+"</td>";d+='<td class="td_sortable"><button class="btn_workflow"  onclick="MINICAVE.prototype._loadState('+c+')">reload</button></td>';return d+="</tr>"},_loadState:function(b){var c=[];c.push({id:b});0==HISTORY_DATA.records[b].requires_json_back?$j.ajax({type:"POST",url:SERVER+"/update",data:"load_state="+encodeURIComponent(JSON.stringify(c))}):$j.ajax({type:"POST",url:SERVER+"/update",
data:"load_state="+encodeURIComponent(JSON.stringify(c)),success:function(c){"histogram"==HISTORY_DATA.records[b].descriptor&&a.prototype._histogram(c,"histogram");"ntracks"==HISTORY_DATA.records[b].descriptor&&a.prototype._ntracks(c)}});if("data"==HISTORY_DATA.records[b].descriptor){HISTORY_DATA.records[b].state.data.sharevol.volume.rotate=HISTORY_DATA.records[b].state.data.sharevol.volume.rotate_quat4;resetFromData(HISTORY_DATA.records[b].state.data.sharevol,!1);if("astro_fits"!=APP_TYPE)for(var d in HISTORY_DATA.records[b].state.data.imagehd)imagehd[d]=
HISTORY_DATA.records[b].state.data.imagehd[d];else for(d in HISTORY_DATA.records[b].state.data.astro)astro[d]=HISTORY_DATA.records[b].state.data.astro[d];for(b in gui.__controllers)gui.__controllers[b].updateDisplay();for(b=0;b<Object.keys(gui.__folders).length;b++)for(c=Object.keys(gui.__folders)[b],d=0;d<gui.__folders[c].__controllers.length;d++)gui.__folders[c].__controllers[d].updateDisplay()}a.prototype._createPanels();1==SAVE_WORKFLOW&&a.prototype._createWorkflowHistory()},_createPanels:function(){var b=
[],c=[];c.push({creating:"panels"});$j.ajax({type:"POST",url:SERVER+"/update",data:"state="+encodeURIComponent(JSON.stringify(c)),success:function(c){"string"===typeof c&&(c=jQuery.parseJSON(c));STATUS=c.status;TOTAL_SCREENS=c.n_nodes*c.n_per_node;N_NODES=c.n_nodes;N_PER_NODE=c.n_per_node;NODES=c.nodes;SAVE_WORKFLOW=c.save_workflow;APP_TYPE=c.app_type;COLUMNS_TO_IGNORE=c.columns_to_ignore;1==SAVE_WORKFLOW&&(WORKFLOW_FILE=c.workflow_data_dir+c.json_filename);this.volume=c.volume;for(var e=cpt=0;e<
c.n_nodes;e++)for(var f=0;f<c.n_per_node;f++)b.push('<li id="screens-li-'+cpt+'" node="'+c.nodes[e].node_id+'" panelScreenNumber="'+c.nodes[e].panels[f].panel_id+'" Subject_ID="'+c.nodes[e].panels[f].file_id+'"></li>'),BEFORESORT[cpt]=c.nodes[e].panels[f].file_id,cpt++;$j("#screensUl").html(b.join(""));for(e=0;e<c.n_nodes;e++)for(f=0;f<c.n_per_node;f++){var g=$j("li[node='"+c.nodes[e].node_id+"'][panelscreennumber$='"+f+"']");"-1"!=c.nodes[e].panels[f].file_id&&g.html(c.nodes[e].panels[f].file_id);
g.addClass("ui-droppable");g.addClass("ui-corner-all");g.prepend("<div class='handle'><span class='ui-icon ui-icon-carat-2-n-s'></span></div>");1==c.nodes[e].panels[f].selection_state&&(g.addClass("ui-selected"),SELECTED_STAMPS.push(g.attr("id")))}$j("#screensUl li").droppable({accept:"#choicesTable tbody tr",drop:function(b,c){if($j(this).hasClass("ui-droppable")){var d="<div class='handle'><span class='ui-icon ui-icon-carat-2-n-s'></span></div>"+c.draggable.find(".td_subject_id").text();if(this.innerHTML!=
d){var f=$j(this).hasClass("ui-selected")?"1":"0";this.innerHTML=d;$j(this).attr("Subject_ID",c.draggable.find(".td_subject_id").text());d=$j("#screensUl").sortable("toArray",{attribute:"Subject_ID"});for(e=0;e<d.length;e++)BEFORESORT[e]=d[e];d=[];d.push({node:$j(this).attr("node"),panel:$j(this).attr("panelScreenNumber"),id:c.draggable.find(".td_subject_id").text(),selected:f});$j.ajax({type:"POST",url:SERVER+"/update",data:"loadOne="+encodeURIComponent(JSON.stringify(d))});1==SAVE_WORKFLOW&&a.prototype._createWorkflowHistory()}}}});
"astro_fits"!=APP_TYPE?$j("#request_from_host").append($j("<option>",{value:"ntracks",text:"ntracks vs age"})):($j("#request_from_host").append($j("<option>",{value:"histogram",text:"histogram"})),$j("#request_from_host").append($j("<option>",{value:"area",text:"area"})),$j("#request_from_host").append($j("<option>",{value:"moment",text:"moment"})));$j("#choicesTable tbody tr").draggable({helper:function(a,b){return"<div>"+$j(this).find(".td_subject_id").text()+"</div>"},cursorAt:{top:0,left:0},snap:"#screensUl li .ui-droppable",
snapMode:"inner",snapTolerance:40,start:function(a,b){$j(this).parent()}});a.prototype._createChoices();$j(":checkbox[id=selectAll]").click(function(){$j(":checkbox[class=inputChkbox]").prop("checked",this.checked)})},error:function(){console.log("Nothing returned on load: s2plot not online.")}})}};MINICAVE=a;new a(json_data)});var volume,slicer,colours,info,colourmaps,props={},reset,filename,mobile,gui;
function initPage(){window.onresize=autoResize;info=new Toolbox("info");info.show();colourmaps=new Toolbox("colourmap",400,200);mobile=760>=screen.width||/Android|webOS|iPhone|iPad|iPod|BlackBerry/i.test(navigator.userAgent);colours=new GradientEditor($("palette"),updateColourmap);var a=getSearchVariable("data");console.log(a);a||((filename=getSearchVariable("img"))?(loadStoredData(filename),props={url:decodeURI(filename),res:[getSearchVariable("nx",256),getSearchVariable("ny",256),getSearchVariable("nz",
256)],scale:[getSearchVariable("dx",1),getSearchVariable("dy",1),getSearchVariable("dz",1)]},props.url&&loadTexture()):a="default.json");a&&($("status").innerHTML="Loading params...",ajaxReadFile(decodeURI(a),loadData,!0));ajaxReadFile("masklist.txt",loadImageHD,!0)}
var imagehd={rotate:!0,labels:!1,trackSamples:.001,trackThickness:2,trackOpacity:.5},astro={show:!1,mip:!1,moment:!1},sort={sort1:0,sort2:0},region={region1:-1,region2:-1,r1alpha:1,r2alpha:1,r1colour:[214,188,86],r2colour:[214,188,86]},regions={None:-1},sortfields={Type:0,Subject_ID:1,Age:2,UHDRS:3,DBS:4,SDMT:5,STAP:6},minicave={showMinicave:!1},virtual_observatory={show:!1};
function loadImageHD(a){a=a.split(/\r\n?|\n/);for(var b in a){var c=a[b];if("#"!=c.charAt(0)){var d=parseInt(c);if(0<d){var c=c.substr(c.indexOf('"')+1),e=c.length-1;28<e&&(e=28);c=c.substr(0,e);regions[c]=d}}}}var server,fi,fs,fr;
function addImageHDGUI(){server="http://"+window.location.host;fi=gui.addFolder("ImageHD");fs=gui.addFolder("Sort");fr=gui.addFolder("Regions");fi.add(imagehd,"labels");fi.add(imagehd,"trackSamples",.001,1,.01);fi.add(imagehd,"trackThickness",.1,10,.1);fi.add(imagehd,"trackOpacity",.1,1,.01);fi.open();fs.add(sort,"sort1",sortfields);fs.add(sort,"sort2",sortfields);fs.add({Update:updateServerSort},"Update");fs.open();fr.add(region,"region1",regions);fr.add(region,"region2",regions);fr.add(region,"r1alpha",
0,1,.01);fr.add(region,"r2alpha",0,1,.01);fr.addColor(region,"r1colour");fr.addColor(region,"r2colour");fr.add({Update:updateServerRegion},"Update");fr.open();for(var a in fi.__controllers)fi.__controllers[a].onChange(updateServerOther);for(a in fs.__controllers)fs.__controllers[a].onChange(updateServerSort);for(a in fr.__controllers)fr.__controllers[a].onChange(updateServerRegion)}
function addAstroGUI(){fa=gui.addFolder("Moment maps");fa.add(astro,"show");fa.add(astro,"mip");fa.add(astro,"moment",[0,1]);fa.open();for(var a in fa.__controllers)fa.__controllers[a].onChange(updateServerOtherAstro)}var serverData=null;
function updateServer(){var a=volume.properties.samples;256>volume.properties.samples&&(volume.properties.samples=256);data=getData(!0,!0);serverData!=data&&(serverData=data,ajaxPost(server+"/update","data="+encodeURIComponent(data)));volume.properties.samples=a;1==SAVE_WORKFLOW&&MINICAVE.prototype._createWorkflowHistory()}
function updateServerOther(){ajaxPost(server+"/update","data="+encodeURIComponent(JSON.stringify(imagehd)));1==SAVE_WORKFLOW&&MINICAVE.prototype._createWorkflowHistory();return!1}function updateServerOtherAstro(){console.log("in updateServerOtherAstro");ajaxPost(server+"/update","moment="+encodeURIComponent(JSON.stringify(astro)));1==SAVE_WORKFLOW&&MINICAVE.prototype._createWorkflowHistory();return!1}
function updateServerSort(){ajaxPost(server+"/update","sort="+encodeURIComponent(JSON.stringify(sort)));try{console.log("in updateServerSort()"),syncScreens()}catch(a){console.log(a.message)}1==SAVE_WORKFLOW&&MINICAVE.prototype._createWorkflowHistory();return!1}function updateServerRegion(){ajaxPost(server+"/update","region="+encodeURIComponent(JSON.stringify(region)));1==SAVE_WORKFLOW&&MINICAVE.prototype._createWorkflowHistory();return!1}function loadStoredData(a){}
function toggleMinicave(){var a=document.getElementById("divMinicave");a.style.display="block"==a.style.display?"none":"block"}function toggleAutospin(a){var b=[];b.push({autospin:a});$j.ajax({type:"POST",url:SERVER+"/update",data:"autospin="+encodeURIComponent(JSON.stringify(b))})}function zoomIn(){var a=[];a.push({dummy:"data"});$j.ajax({type:"POST",url:SERVER+"/update",data:"zoomIn="+encodeURIComponent(JSON.stringify(a))})}
function zoomOut(){var a=[];a.push({dummy:"data"});$j.ajax({type:"POST",url:SERVER+"/update",data:"zoomOut="+encodeURIComponent(JSON.stringify(a))})}function showStats(){var a=[];a.push({dummy:"data"});$j.ajax({type:"POST",url:SERVER+"/update",data:"showStats="+encodeURIComponent(JSON.stringify(a))})}
function StopEncubePR(){if(confirm("Are you sure you want to stop encube-PR?")){var a=[];a.push({node:$j(".ui-selected").attr("node"),panel:$j(".ui-selected").attr("panelScreenNumber")});$j.ajax({type:"POST",url:SERVER+"/update",data:"stopEncubePR="+encodeURIComponent(JSON.stringify(a))})}}
function loadData(a,b){reset=props=JSON.parse(a);getSearchVariable("reset")&&(localStorage.removeItem(b),console.log("Storage cleared"));filename=b;loadStoredData(b);props.url=reset.url;props.res=reset.res||[256,256,256];props.scale=reset.scale||[1,1,1];loadTexture()}
function loadDataFromJson(a){reset=props=JSON.parse(a);getSearchVariable("reset")&&(localStorage.removeItem(fn),console.log("Storage cleared"));filename=fn;loadStoredData(fn);props.url=reset.url;props.res=reset.res||[256,256,256];props.scale=reset.scale||[1,1,1];loadTexture()}function saveData(){try{localStorage[filename]=getData()}catch(a){console.log("LocalStorage Error: Quota exceeded? "+a)}}
function getData(a,b){var c={};c.url=props.url;c.res=props.res;c.scale=props.scale;volume&&(c.volume=volume.get(b));slicer&&(c.slicer=slicer.get());return a?JSON.stringify(c):JSON.stringify(c,null,2)}function exportData(){window.open("data:text/json;base64,"+window.btoa(getData()))}function resetFromData(a,b){a.volume&&volume&&(volume.load(a.volume),volume.draw(b));a.slicer&&slicer&&(slicer.load(a.slicer),slicer.draw())}
function loadTexture(){$("status").innerHTML="Loading image data... ";var a;loadImage(props.url,function(){a=new Image;var b=request.getAllResponseHeaders().match(/^Content-Type\:\s*(.*?)$/mi)[1]||"image/png",b=new Blob([request.response],{type:b});a.src=window.URL.createObjectURL(b);document.createElement("img");a.onload=function(){console.log("Loaded image: "+a.width+" x "+a.height);imageLoaded(a)}})}
function imageLoaded(a){props.slicer&&(mobile&&(props.slicer.show=!1),slicer=new Slicer(props,a,"linear"));props.volume&&(volume=new Volume(props,a,mobile),volume.slicer=slicer,volume.samples=64);document.addEventListener("mouseup",function(a){volume&&volume.delayedRender(250,!0)},!1);document.addEventListener("wheel",function(a){volume&&volume.delayedRender(250,!0)},!1);updateColourmap();info.hide();props.nogui||(gui=new dat.GUI({width:400}),gui.add({Reset:function(){resetFromData(reset,!0)}},"Reset"),
gui.add({"Stop encube-PR":function(){StopEncubePR()}},"Stop encube-PR"),gui.add(imagehd,"rotate").onChange(function(a){volume.flipbuttons=!a}),a=gui.addFolder("S2PLOT options"),a.add({Autospin:!1},"Autospin").onChange(function(a){toggleAutospin(a)}),a.add({"Zoom in":function(){zoomIn()}},"Zoom in"),a.add({"Zoom out":function(){zoomOut()}},"Zoom out"),a.add({"Show stats":function(){showStats()}},"Show stats"),a.open(),a=gui.addFolder("Miniature CAVE2"),a.add(minicave,"showMinicave").onChange(toggleMinicave),
a.open(),"astro_fits"!=APP_TYPE?addImageHDGUI():(gui.add({ColourMaps:function(){window.colourmaps.toggle()}},"ColourMaps"),addAstroGUI()),volume&&volume.addGUI(gui),slicer&&slicer.addGUI(gui));window.onbeforeunload=saveData}function fileSelected(a){filesProcess(a)}function filesProcess(a,b){window.URL=window.webkitURL||window.URL;for(var c=0;c<a.length;c++)props.url=window.URL.createObjectURL(a[c]),loadTexture()}function autoResize(){volume&&(volume.width=0,volume.height=0,volume.draw(!0))}
function setColourMap(a){a=readURL("colourmaps/"+a);colours.read(a);updateColourmap()}function updateColourmap(){if(colours){var a=$("gradient");colours.palette.draw(a,!1);volume&&volume.webgl&&(volume.properties.colourmap_url=a.toDataURL(),volume.webgl.updateTexture(volume.webgl.gradientTexture,a,volume.gl.TEXTURE1),volume.applyBackground(colours.palette.background.html()),volume.draw(!0));slicer&&(slicer.updateColourmap(),slicer.draw())}}var request,progressBar;
function loadImage(a,b){request=new XMLHttpRequest;request.onloadstart=showProgressBar;request.onprogress=updateProgressBar;request.onload=b;request.onloadend=hideProgressBar;request.open("GET",a,!0);request.responseType="arraybuffer";request.send(null)}function showProgressBar(){progressBar=document.createElement("progress");progressBar.value=0;progressBar.max=100;progressBar.removeAttribute("value");document.getElementById("status").appendChild(progressBar)}
function updateProgressBar(a){a.lengthComputable?progressBar.value=a.loaded/a.total*100:progressBar.removeAttribute("value")}function showImage(){var a=request.getAllResponseHeaders().match(/^Content-Type\:\s*(.*?)$/mi)[1]||"image/png",a=new Blob([request.response],{type:a}),b=document.createElement("img");b.src=window.URL.createObjectURL(a);document.body.appendChild(b)}function hideProgressBar(){document.getElementById("status").removeChild(progressBar)}
function Toolbox(a,b,c){this.el=$(a);this.mouse=new Mouse(this.el,this);this.mouse.moveUpdate=!0;this.el.mouse=this.mouse;this.style=$S(a);b&&c?(this.style.left=b+"px",this.style.top=c+"px"):(this.style.left=.5*(window.innerWidth-this.el.offsetWidth)+"px",this.style.top=.5*(window.innerHeight-this.el.offsetHeight)+"px");this.drag=!1}Toolbox.prototype.toggle=function(){"visible"==this.style.visibility?this.hide():this.show()};Toolbox.prototype.show=function(){this.style.visibility="visible"};
Toolbox.prototype.hide=function(){this.style.visibility="hidden"};Toolbox.prototype.click=function(a,b){this.drag=!1;return!0};Toolbox.prototype.down=function(a,b){this.drag=!1;0==b.button&&0>a.target.className.indexOf("scroll")&&0>["INPUT","SELECT","OPTION","RADIO"].indexOf(a.target.tagName)&&(this.drag=!0);return!0};
Toolbox.prototype.move=function(a,b){if(!b.isdown||!this.drag)return!0;this.el.style.left=parseInt(this.el.style.left)+b.deltaX+"px";this.el.style.top=parseInt(this.el.style.top)+b.deltaY+"px";return!1};Toolbox.prototype.wheel=function(a,b){};
function Slicer(a,b,c,d){this.image=b;this.res=a.res;this.dims=[a.res[0]*a.scale[0],a.res[1]*a.scale[1],a.res[2]*a.scale[2]];this.slices=[.5,.5,.5];this.properties={};this.properties.show=!0;this.properties.X=Math.round(this.res[0]/2);this.properties.Y=Math.round(this.res[1]/2);this.properties.Z=Math.round(this.res[2]/2);this.properties.brightness=0;this.properties.contrast=1;this.properties.power=1;this.properties.usecolourmap=!1;this.properties.layout="xyz";this.flipY=!1;this.properties.zoom=1;
this.container=document.createElement("div");this.container.style.cssText="position: absolute; bottom: 10px; left: 10px; margin: 0px; padding: 0px; pointer-events: none;";d||(d=document.body);d.appendChild(this.container);a.slicer&&this.load(a.slicer);this.canvas=document.createElement("canvas");this.canvas.style.cssText="position: absolute; bottom: 0px; margin: 0px; padding: 0px; border: none; background: rgba(0,0,0,0); pointer-events: none;";this.doLayout();this.canvas.mouse=new Mouse(this.canvas,
this);this.webgl=new WebGL(this.canvas);this.gl=this.webgl.gl;this.filter=this.gl.NEAREST;"linear"==c&&(this.filter=this.gl.LINEAR);this.webgl.init2dBuffers(this.gl.TEXTURE2);this.program=new WebGLProgram(this.gl,"texture-vs","texture-fs");this.program.errors&&OK.debug(this.program.errors);this.program.setup(["aVertexPosition"],"palette texture colourmap cont bright power slice dim res axis select".split(" "));this.gl.clearColor(0,0,0,0);this.gl.enable(this.gl.BLEND);this.gl.blendFunc(this.gl.SRC_ALPHA,
this.gl.ONE_MINUS_SRC_ALPHA);this.gl.enable(this.gl.SCISSOR_TEST);this.loadImage(this.image);this.properties.show||this.toggle()}Slicer.prototype.toggle=function(){this.container.style.visibility="hidden"==this.container.style.visibility?"visible":"hidden"};
Slicer.prototype.addGUI=function(a){this.gui=a;var b=this;a=this.gui.addFolder("Slices");a.add(this.properties,"show").onFinishChange(function(a){b.toggle()});a.add(this.properties,"layout").onFinishChange(function(a){b.doLayout();b.draw()});a.add(this.properties,"zoom",.01,4,.1).onFinishChange(function(a){b.doLayout();b.draw()});a.add(this.properties,"brightness",-1,1,.01);a.add(this.properties,"contrast",0,3,.01);a.add(this.properties,"power",.01,5,.01);a.add(this.properties,"usecolourmap");a.open();
var c=function(a){b.draw()},d;for(d in a.__controllers)a.__controllers[d].onChange(c)};Slicer.prototype.get=function(){var a={};a.properties=this.properties;return a};Slicer.prototype.load=function(a){for(var b in a.properties)this.properties[b]=a.properties[b]};Slicer.prototype.setX=function(a){this.properties.X=a*this.res[0];this.draw()};Slicer.prototype.setY=function(a){this.properties.Y=a*this.res[1];this.draw()};Slicer.prototype.setZ=function(a){this.properties.Z=a*this.res[2];this.draw()};
Slicer.prototype.doLayout=function(){this.viewers=[];var a=0,b=0,c=0,d=0,e=!0;removeChildren(this.container);var f=this,g="",k=0,n=function(e){var h=1;g&&(h=parseFloat(g));e=new SliceView(f,a,b,e,d,h);f.viewers.push(e);f.container.appendChild(e.div);b+=e.viewport.height+5;e=e.viewport.width+5;e>k&&(k=e);b>c&&(c=b)};this.flipY=!1;for(var h=0;h<this.properties.layout.length;h++){var l=this.properties.layout.charAt(h),d=0;switch(l){case "X":d=90;case "x":n(0);break;case "Y":d=90;case "y":n(1);break;
case "Z":d=90;case "z":n(2);break;case "|":b=0;a+=k;k=0;break;case "_":this.flipY=!0;break;case "-":e=!1;break;default:g+=l;continue}g=""}this.width=a+k;this.height=c;this.container.appendChild(this.canvas);e?(this.container.style.bottom="",this.container.style.top=this.height+10+"px"):(this.container.style.top=void 0,this.container.style.bottom="10px")};Slicer.prototype.loadImage=function(a){for(var b=0;3>b;b++)this.webgl.loadTexture(a,this.filter);this.reset()};
Slicer.prototype.reset=function(){this.dimx=this.image.width/this.res[0];this.dimy=this.image.height/this.res[1]};Slicer.prototype.updateColourmap=function(){this.webgl.updateTexture(this.webgl.gradientTexture,$("gradient"),this.gl.TEXTURE2);this.draw()};
Slicer.prototype.draw=function(){this.slices=[(this.properties.X-1)/(this.res[0]-1),(this.properties.Y-1)/(this.res[1]-1),(this.properties.Z-1)/(this.res[2]-1)];if(this.width!=this.canvas.width||this.height!=this.canvas.height)this.canvas.width=this.width,this.canvas.height=this.height,this.canvas.setAttribute("width",this.width),this.canvas.setAttribute("height",this.height),this.webgl&&(this.gl.viewportWidth=this.width,this.gl.viewportHeight=this.height,this.webgl.viewport=new Viewport(0,0,this.width,
this.height));this.webgl.use(this.program);this.gl.uniform4fv(this.program.uniforms.background,colours.palette.colours[0].colour.rgbaGL());this.gl.activeTexture(this.gl.TEXTURE0);this.gl.bindTexture(this.gl.TEXTURE_2D,this.webgl.gradientTexture);this.gl.uniform1i(this.program.uniforms.palette,0);this.gl.uniform1i(this.program.uniforms.colourmap,this.properties.usecolourmap);this.gl.uniform1f(this.program.uniforms.bright,this.properties.brightness);this.gl.uniform1f(this.program.uniforms.cont,this.properties.contrast);
this.gl.uniform1f(this.program.uniforms.power,this.properties.power);this.gl.activeTexture(this.gl.TEXTURE1);this.gl.bindTexture(this.gl.TEXTURE_2D,this.webgl.textures[0]);this.gl.uniform1i(this.program.uniforms.texture,1);this.gl.scissor(0,0,this.width,this.height);this.gl.clear(this.gl.COLOR_BUFFER_BIT|this.gl.DEPTH_BUFFER_BIT);for(var a=0;a<this.viewers.length;a++)this.drawSlice(a)};
Slicer.prototype.drawSlice=function(a){a=this.viewers[a];var b=a.viewport,c;c=90==a.rotate?[1-this.slices[a.j],this.slices[a.i]]:[this.slices[a.i],this.slices[a.j]];this.flipY||(c[1]=1-c[1]);this.webgl.viewport=b;this.gl.scissor(b.x,b.y,b.width,b.height);this.webgl.modelView.identity();this.webgl.modelView.translate([.5,.5,0]);this.webgl.modelView.rotate(-a.rotate,[0,0,1]);var d=[.5,-.5,-1];this.flipY&&(d[1]=-d[1]);this.webgl.modelView.scale(d);this.gl.uniform3f(this.program.uniforms.slice,this.slices[0],
this.slices[1],this.slices[2]);this.gl.uniform2f(this.program.uniforms.dim,this.dimx,this.dimy);this.gl.uniform3i(this.program.uniforms.res,this.res[0],this.res[1],this.res[2]);this.gl.uniform1i(this.program.uniforms.axis,a.axis);this.gl.uniform2i(this.program.uniforms.select,b.width*c[0]+b.x,b.height*c[1]+b.y);this.webgl.initDraw2d();this.gl.enable(this.gl.BLEND);this.gl.blendFunc(this.gl.SRC_ALPHA,this.gl.ONE_MINUS_SRC_ALPHA);this.gl.drawArrays(this.gl.TRIANGLE_STRIP,0,this.webgl.vertexPositionBuffer.numItems)};
function SliceView(a,b,c,d,e,f){this.axis=d;this.slicer=a;this.magnify=f||1;this.origin=[.5,.5];this.rotate=e||0;this.i=0;this.j=1;0==d&&(this.i=2);1==d&&(this.j=2);e=Math.round(a.dims[this.i]*a.properties.zoom*this.magnify);a=Math.round(a.dims[this.j]*a.properties.zoom*this.magnify);this.viewport=90==this.rotate?new Viewport(b,c,a,e):new Viewport(b,c,e,a);this.div=document.createElement("div");this.div.style.cssText="padding: 0px; margin: 0px; outline: 2px solid rgba(64,64,64,0.5); position: absolute; display: inline-block; pointer-events: auto;";
this.div.id="slice-div-"+d;this.div.style.left=b+"px";this.div.style.bottom=c+"px";this.div.style.width=this.viewport.width+"px";this.div.style.height=this.viewport.height+"px";this.div.mouse=new Mouse(this.div,this)}
SliceView.prototype.click=function(a,b){this.slicer.flipY&&(b.y=b.element.clientHeight-b.y);var c;c=90==this.rotate?[b.y/b.element.clientHeight,1-b.x/b.element.clientWidth]:[b.x/b.element.clientWidth,b.y/b.element.clientHeight];var d=Math.round(this.slicer.res[this.i]*c[0]);c=Math.round(this.slicer.res[this.j]*c[1]);0==this.axis?(slicer.properties.Z=d,slicer.properties.Y=c):1==this.axis?(slicer.properties.X=d,slicer.properties.Z=c):(slicer.properties.X=d,slicer.properties.Y=c);this.slicer.draw()};
SliceView.prototype.wheel=function(a,b){0==this.axis&&(slicer.properties.X+=a.spin);1==this.axis&&(slicer.properties.Y+=a.spin);2==this.axis&&(slicer.properties.Z+=a.spin);this.slicer.draw()};SliceView.prototype.move=function(a,b){b.isdown&&this.click(a,b)};
function Volume(a,b,c,d){this.image=b;this.canvas=document.createElement("canvas");this.canvas.style.cssText="width: 100%; height: 100%; z-index: 0; margin: 0px; padding: 0px; background: black; border: none; display:block;";d||(d=document.body);d.appendChild(this.canvas);this.canvas.mouse=new Mouse(this.canvas,this);this.canvas.mouse.moveUpdate=!0;this.background=new Colour(4282400832);this.borderColour=new Colour(4290493371);this.width=this.height=0;this.webgl=new WebGL(this.canvas);this.gl=this.webgl.gl;
this.rotating=this.flipbuttons=!1;this.translate=[0,0,4];this.rotate=quat4.create();quat4.identity(this.rotate);this.focus=[0,0,0];this.centre=[0,0,0];this.modelsize=1;this.scale=[1,1,1];this.orientation=1;this.fov=45;this.focalLength=1/Math.tan(.5*this.fov*Math.PI/180);this.resolution=a.res;this.scaling=[a.res[0]*a.scale[0],a.res[1]*a.scale[1],a.res[2]*a.scale[2]];this.tiles=[this.image.width/a.res[0],this.image.height/a.res[1]];d=a.res[2];this.scaling=[d/this.scaling[0],d/this.scaling[1],d/this.scaling[2]];
this.centre=[.5/this.scaling[0],.5/this.scaling[1],.5/this.scaling[2]];this.modelsize=Math.sqrt(3);this.focus=this.centre;this.translate[2]=1.25*-this.modelsize;OK.debug("New model size: "+this.modelsize+", Focal point: "+this.focus[0]+","+this.focus[1]+","+this.focus[2]);this.linePositionBuffer=this.gl.createBuffer();this.gl.bindBuffer(this.gl.ARRAY_BUFFER,this.linePositionBuffer);this.gl.bufferData(this.gl.ARRAY_BUFFER,new Float32Array([-1,0,0,1,0,0,0,-1,0,0,1,0,0,0,-1,0,0,1]),this.gl.STATIC_DRAW);
this.linePositionBuffer.itemSize=3;this.linePositionBuffer.numItems=6;this.lineColourBuffer=this.gl.createBuffer();this.gl.bindBuffer(this.gl.ARRAY_BUFFER,this.lineColourBuffer);this.gl.bufferData(this.gl.ARRAY_BUFFER,new Float32Array([1,0,0,1,1,0,0,1,0,1,0,1,0,1,0,1,0,0,1,1,0,0,1,1]),this.gl.STATIC_DRAW);this.lineColourBuffer.itemSize=4;this.lineColourBuffer.numItems=6;this.webgl.init2dBuffers(this.gl.TEXTURE1);this.gl.texParameteri(this.gl.TEXTURE_2D,this.gl.TEXTURE_WRAP_S,this.gl.CLAMP_TO_EDGE);
this.gl.texParameteri(this.gl.TEXTURE_2D,this.gl.TEXTURE_WRAP_T,this.gl.CLAMP_TO_EDGE);this.webgl.loadTexture(b,this.gl.LINEAR);d=!!window.MSInputMethodContext;this.lineprogram=new WebGLProgram(this.gl,"line-vs","line-fs");this.lineprogram.errors&&OK.debug(this.lineprogram.errors);this.lineprogram.setup(["aVertexPosition","aVertexColour"],["uColour","uAlpha"]);this.gl.vertexAttribPointer(this.lineprogram.attributes.aVertexPosition,this.linePositionBuffer.itemSize,this.gl.FLOAT,!1,0,0);this.gl.vertexAttribPointer(this.lineprogram.attributes.aVertexColour,
this.lineColourBuffer.itemSize,this.gl.FLOAT,!1,0,0);a.volume.properties.disabled||(b="precision highp float; const highp vec2 slices = vec2("+this.tiles[0]+","+this.tiles[1]+");\n",b=b+(d?"#define IE11\n":"#define NOT_IE11\n")+("const int maxSamples = "+(c?256:1024)+";\n\n\n\n\n\n"),OK.debug(b),d=getSourceFromElement("ray-fs"),this.program=new WebGLProgram(this.gl,"ray-vs",b+d),this.program.errors&&OK.debug(this.program.errors),this.program.setup(["aVertexPosition"],"uBackCoord uVolume uTransferFunction uEnableColour uFilter uDensityFactor uPower uBrightness uContrast uSamples uFocalLength uWindowSize uBBMin uBBMax uResolution uIsoValue uIsoColour uIsoSmooth uIsoWalls".split(" ")));
this.gl.enable(this.gl.DEPTH_TEST);this.gl.clearColor(0,0,0,0);this.gl.enable(this.gl.BLEND);this.gl.blendFunc(this.gl.SRC_ALPHA,this.gl.ONE_MINUS_SRC_ALPHA);this.gl.depthFunc(this.gl.LEQUAL);this.properties={};this.properties.samples=256;this.properties.isovalue=0;this.properties.drawWalls=!1;this.properties.isoalpha=.75;this.properties.isosmooth=1;this.properties.isocolour=[255,0,0];this.properties.Xmin=this.properties.Ymin=this.properties.Zmin=0;this.properties.Xmax=this.properties.Ymax=this.properties.Zmax=
1;this.properties.density=10;this.properties.brightness=0;this.properties.contrast=1;this.properties.power=1;this.properties.usecolourmap=!1;this.properties.colourmap_url="";this.properties.tricubicFilter=!1;this.properties.lowPowerDevice=!1;this.properties.disabled=!1;this.properties.axes=!0;this.properties.border=!0;a.volume&&this.load(a.volume);this.clipChanged();c&&(this.properties.lowPowerDevice=!0)}
Volume.prototype.box=function(a,b){var c=new Float32Array([a[0],a[1],b[2],a[0],b[1],b[2],b[0],b[1],b[2],b[0],a[1],b[2],a[0],a[1],a[2],a[0],b[1],a[2],b[0],b[1],a[2],b[0],a[1],a[2]]);this.boxPositionBuffer||(this.boxPositionBuffer=this.gl.createBuffer());this.gl.bindBuffer(this.gl.ARRAY_BUFFER,this.boxPositionBuffer);this.gl.bufferData(this.gl.ARRAY_BUFFER,c,this.gl.STATIC_DRAW);this.boxPositionBuffer.itemSize=3;this.boxIndexBuffer||(c=new Uint16Array([0,1,1,2,2,3,3,0,4,5,5,6,6,7,7,4,0,4,3,7,1,5,2,
6]),this.boxIndexBuffer=this.gl.createBuffer(),this.gl.bindBuffer(this.gl.ELEMENT_ARRAY_BUFFER,this.boxIndexBuffer),this.gl.bufferData(this.gl.ELEMENT_ARRAY_BUFFER,c,this.gl.STATIC_DRAW),this.boxIndexBuffer.numItems=24)};
Volume.prototype.addGUI=function(a){this.gui&&this.gui.destroy();var b=this;this.gui=a;a=this.gui.addFolder("Volume");a.add(this.properties,"lowPowerDevice");a.add(this.properties,"usecolourmap");this.properties.samples=Math.floor(this.properties.samples);0<this.properties.samples%32&&(this.properties.samples-=this.properties.samples%32);a.add(this.properties,"samples",32,1024,32);a.add(this.properties,"density",0,50,1);a.add(this.properties,"brightness",-1,1,.05);a.add(this.properties,"contrast",
0,3,.05);a.add(this.properties,"power",.01,5,.05);a.add(this.properties,"axes");a.add(this.properties,"border");a.add(this.properties,"tricubicFilter");a.open();var c=function(){b.clipChanged()},d=this.gui.addFolder("Clip planes");d.add(this.properties,"Xmin",0,1,.01).onFinishChange(c);d.add(this.properties,"Xmax",0,1,.01).onFinishChange(c);d.add(this.properties,"Ymin",0,1,.01).onFinishChange(c);d.add(this.properties,"Ymax",0,1,.01).onFinishChange(c);d.add(this.properties,"Zmin",0,1,.01).onFinishChange(c);
d.add(this.properties,"Zmax",0,1,.01).onFinishChange(c);c=this.gui.addFolder("Isosurface");c.add(this.properties,"isovalue",0,1,.01);c.add(this.properties,"drawWalls");c.add(this.properties,"isoalpha",0,1,.01);c.add(this.properties,"isosmooth",.1,3,.1);c.addColor(this.properties,"isocolour");c.open();var e=function(a){b.delayedRender(250)},f;for(f in a.__controllers)a.__controllers[f].onChange(e);for(f in d.__controllers)d.__controllers[f].onChange(e);for(f in c.__controllers)c.__controllers[f].onChange(e)};
Volume.prototype.clipChanged=function(){this.box([this.properties.Xmin,this.properties.Ymin,this.properties.Zmin],[this.properties.Xmax,this.properties.Ymax,this.properties.Zmax])};
Volume.prototype.load=function(a){colours.read(a.colourmap);colours.update();for(var b in a.properties)this.properties[b]=a.properties[b];a.translate&&(this.translate=a.translate);a.rotate&&(3==a.rotate.length?(this.rotateZ(-a.rotate[2]),this.rotateY(-a.rotate[1]),this.rotateX(-a.rotate[0])):0!=a.rotate[3]&&(this.rotate=quat4.create(a.rotate)))};
Volume.prototype.get=function(a){var b={};a?(a=quat4.toMat3(this.rotate),b.rotate=[a[0],a[1],a[2],a[3],a[4],a[5],a[6],a[7],a[8]],b.rotate_quat4=this.rotate):b.rotate=[this.rotate[0],this.rotate[1],this.rotate[2],this.rotate[3]];b.translate=this.translate;b.colourmap=colours.palette.toString();b.properties=this.properties;return b};var frames=0,testtime;
Volume.prototype.draw=function(a,b,c){if(this.properties&&this.webgl){if(0==this.width||0==this.height)this.width=window.innerWidth,this.height=window.innerHeight;if(this.width!=this.canvas.width||this.height!=this.canvas.height)this.canvas.width=this.width,this.canvas.height=this.height,this.canvas.setAttribute("width",this.width),this.canvas.setAttribute("height",this.height),this.gl&&(this.gl.viewportWidth=this.width-300,this.gl.viewportHeight=this.height,this.webgl.viewport=new Viewport(0,0,this.width-
300,this.height));this.camera();this.gl.clear(this.gl.COLOR_BUFFER_BIT|this.gl.DEPTH_BUFFER_BIT);this.gl.viewport(this.webgl.viewport.x,this.webgl.viewport.y,this.webgl.viewport.width,this.webgl.viewport.height);this.properties.axes&&this.drawAxis(1);this.properties.border&&this.drawBox(1);this.camera();if(b&&this.properties.lowPowerDevice||this.properties.disabled)this.properties.axes||this.drawAxis(1),this.drawBox(1);else{this.webgl.use(this.program);this.webgl.modelView.scale(this.scaling);this.gl.disableVertexAttribArray(this.program.attributes.aVertexColour);
this.gl.activeTexture(this.gl.TEXTURE0);this.gl.bindTexture(this.gl.TEXTURE_2D,this.webgl.textures[0]);this.gl.activeTexture(this.gl.TEXTURE1);this.gl.bindTexture(this.gl.TEXTURE_2D,this.webgl.gradientTexture);this.gl.uniform1i(this.program.uniforms.uSamples,b?.5*this.properties.samples:this.properties.samples);this.gl.uniform1i(this.program.uniforms.uVolume,0);this.gl.uniform1i(this.program.uniforms.uTransferFunction,1);this.gl.uniform1i(this.program.uniforms.uEnableColour,this.properties.usecolourmap);
this.gl.uniform1i(this.program.uniforms.uFilter,b?!1:this.properties.tricubicFilter);this.gl.uniform1f(this.program.uniforms.uFocalLength,this.focalLength);this.gl.uniform2fv(this.program.uniforms.uWindowSize,new Float32Array([this.gl.viewportWidth,this.gl.viewportHeight]));var d=[this.properties.Xmax,this.properties.Ymax,this.properties.Zmax];this.gl.uniform3fv(this.program.uniforms.uBBMin,new Float32Array([this.properties.Xmin,this.properties.Ymin,this.properties.Zmin]));this.gl.uniform3fv(this.program.uniforms.uBBMax,
new Float32Array(d));this.gl.uniform3fv(this.program.uniforms.uResolution,new Float32Array(this.resolution));this.gl.uniform1f(this.program.uniforms.uDensityFactor,this.properties.density);this.gl.uniform1f(this.program.uniforms.uBrightness,this.properties.brightness);this.gl.uniform1f(this.program.uniforms.uContrast,this.properties.contrast);this.gl.uniform1f(this.program.uniforms.uPower,this.properties.power);this.gl.uniform1f(this.program.uniforms.uIsoValue,this.properties.isovalue);d=new Colour(this.properties.isocolour);
d.alpha=this.properties.isoalpha;this.gl.uniform4fv(this.program.uniforms.uIsoColour,d.rgbaGL());this.gl.uniform1f(this.program.uniforms.uIsoSmooth,this.properties.isosmooth);this.gl.uniform1i(this.program.uniforms.uIsoWalls,this.properties.drawWalls);this.webgl.initDraw2d();this.gl.drawArrays(this.gl.TRIANGLE_STRIP,0,this.webgl.vertexPositionBuffer.numItems)}this.properties.axes&&(this.gl.clear(this.gl.DEPTH_BUFFER_BIT),this.camera(),this.drawAxis(.2));this.properties.border&&(this.camera(),this.drawBox(.2));
c&&(frames++,$("status").innerHTML="Speed test: frame "+frames,5==frames?(c=(new Date).getTime()-testtime,console.log("5 frames in "+c/1E3+" seconds"),1E3<c?(this.properties.samples=Math.floor(1E3*this.properties.samples/c),32>this.properties.samples&&(this.properties.samples=32),$("status").innerHTML="5 frames in "+c/1E3+" seconds, Reduced quality to "+this.properties.samples,setTimeout(function(){info.hide()},2E3)):info.hide()):this.draw(!0,!0,!0));a&&(b||updateServer())}};
Volume.prototype.camera=function(){this.webgl.modelView.identity();this.webgl.modelView.translate(this.translate);adjust=[-(this.focus[0]-this.centre[0]),-(this.focus[1]-this.centre[1]),-(this.focus[2]-this.centre[2])];this.webgl.modelView.translate(adjust);var a=quat4.toMat4(this.rotate);this.webgl.modelView.mult(a);adjust=[this.focus[0]-this.centre[0],this.focus[1]-this.centre[1],this.focus[2]-this.centre[2]];this.webgl.modelView.translate(adjust);this.webgl.modelView.translate([-this.focus[0],
-this.focus[1],-this.focus[2]*this.orientation]);this.webgl.setPerspective(this.fov,this.gl.viewportWidth/this.gl.viewportHeight,.1,100)};
Volume.prototype.drawAxis=function(a){this.webgl.use(this.lineprogram);this.gl.uniform1f(this.lineprogram.uniforms.uAlpha,a);this.gl.uniform4fv(this.lineprogram.uniforms.uColour,new Float32Array([1,1,1,0]));this.gl.bindBuffer(this.gl.ARRAY_BUFFER,this.linePositionBuffer);this.gl.enableVertexAttribArray(this.lineprogram.attributes.aVertexPosition);this.gl.vertexAttribPointer(this.lineprogram.attributes.aVertexPosition,this.linePositionBuffer.itemSize,this.gl.FLOAT,!1,0,0);this.gl.bindBuffer(this.gl.ARRAY_BUFFER,
this.lineColourBuffer);this.gl.enableVertexAttribArray(this.lineprogram.attributes.aVertexColour);this.gl.vertexAttribPointer(this.lineprogram.attributes.aVertexColour,this.lineColourBuffer.itemSize,this.gl.FLOAT,!1,0,0);a=[.5/this.scaling[0],.5/this.scaling[1],.5/this.scaling[2]];this.slicer&&(a=[this.slicer.slices[0]/this.scaling[0],this.slicer.slices[1]/this.scaling[1],this.slicer.slices[2]/this.scaling[2]]);this.webgl.modelView.translate(a);this.webgl.setMatrices();this.gl.drawArrays(this.gl.LINES,
0,this.linePositionBuffer.numItems);this.webgl.modelView.translate([-a[0],-a[1],-a[2]])};
Volume.prototype.drawBox=function(a){this.webgl.use(this.lineprogram);this.gl.uniform1f(this.lineprogram.uniforms.uAlpha,a);this.gl.uniform4fv(this.lineprogram.uniforms.uColour,this.borderColour.rgbaGL());this.gl.bindBuffer(this.gl.ARRAY_BUFFER,this.boxPositionBuffer);this.gl.bindBuffer(this.gl.ELEMENT_ARRAY_BUFFER,this.boxIndexBuffer);this.gl.enableVertexAttribArray(this.lineprogram.attributes.aVertexPosition);this.gl.vertexAttribPointer(this.lineprogram.attributes.aVertexPosition,this.boxPositionBuffer.itemSize,
this.gl.FLOAT,!1,0,0);this.gl.vertexAttribPointer(this.lineprogram.attributes.aVertexColour,4,this.gl.UNSIGNED_BYTE,!0,0,0);this.webgl.modelView.scale([1/this.scaling[0],1/this.scaling[1],1/this.scaling[2]]);this.webgl.setMatrices();this.gl.drawElements(this.gl.LINES,this.boxIndexBuffer.numItems,this.gl.UNSIGNED_SHORT,0)};
Volume.prototype.timeAction=function(a,b){function c(){var b=(new Date).getTime()-d;50>b?window.requestAnimationFrame(c):console.log(a+" took: "+b/1E3+" seconds")}if(window.requestAnimationFrame){var d=b||(new Date).getTime();window.requestAnimationFrame(c)}};Volume.prototype.rotateX=function(a){this.rotation(a,[1,0,0])};Volume.prototype.rotateY=function(a){this.rotation(a,[0,1,0])};Volume.prototype.rotateZ=function(a){this.rotation(a,[0,0,1])};
Volume.prototype.rotation=function(a,b){var c=quat4.fromAngleAxis(a*Math.PI/180,b),c=quat4.normalize(c);this.rotate=quat4.multiply(c,this.rotate)};Volume.prototype.zoom=function(a){this.translate[2]+=a*this.modelsize};Volume.prototype.zoomClip=function(a){this.draw(!0)};Volume.prototype.click=function(a,b){this.rotating=!1;this.draw(!0);return!1};
Volume.prototype.move=function(a,b){this.rotating=!1;if(!b.isdown)return!0;var c=b.button;this.flipbuttons&&1!=c&&(c=0==c?2:0);switch(c){case 0:this.rotateY(b.deltaX/5);this.rotateX(b.deltaY/5);this.rotating=!0;break;case 1:this.rotateZ(Math.sqrt(b.deltaX*b.deltaX+b.deltaY*b.deltaY)/5);this.rotating=!0;break;case 2:c=this.modelsize/1E3,this.translate[0]+=b.deltaX*c,this.translate[1]-=b.deltaY*c}this.draw(!0,!0);return!1};
Volume.prototype.wheel=function(a,b){if(a.shiftKey){var c=.01*a.spin;this.zoomClip(c)}else c=.05*a.spin,this.zoom(c);this.delayedRender(250);return!1};Volume.prototype.pinch=function(a,b){var c=1E-4*a.distance;console.log(" --\x3e "+c);this.zoom(c);this.delayedRender(250)};Volume.prototype.delayedRender=function(a,b){b||this.draw(!0,!0);this.delaytimer&&clearTimeout(this.delaytimer);var c=this;this.delaytimer=setTimeout(function(){c.draw(!0)},a)};
Volume.prototype.applyBackground=function(a){a&&(this.background=new Colour(a),this.borderColour=50<this.background.HSV().V?new Colour(4282664004):new Colour(4290493371),this.canvas.style.backgroundColor=this.properties.usecolourmap?a:"black")};
function Toolbox(a,b,c){this.el=$(a);this.mouse=new Mouse(this.el,this);this.mouse.moveUpdate=!0;this.el.mouse=this.mouse;this.style=$S(a);b&&c?(this.style.left=b+"px",this.style.top=c+"px"):(this.style.left=.5*(window.innerWidth-this.el.offsetWidth)+"px",this.style.top=.5*(window.innerHeight-this.el.offsetHeight)+"px");this.drag=!1}Toolbox.prototype.toggle=function(){"visible"==this.style.visibility?this.hide():this.show()};Toolbox.prototype.show=function(){this.style.visibility="visible"};
Toolbox.prototype.hide=function(){this.style.visibility="hidden"};Toolbox.prototype.click=function(a,b){this.drag=!1;return!0};Toolbox.prototype.down=function(a,b){this.drag=!1;0==b.button&&0>a.target.className.indexOf("scroll")&&0>["INPUT","SELECT","OPTION","RADIO"].indexOf(a.target.tagName)&&(this.drag=!0);return!0};
Toolbox.prototype.move=function(a,b){if(!b.isdown||!this.drag)return!0;this.el.style.left=parseInt(this.el.style.left)+b.deltaX+"px";this.el.style.top=parseInt(this.el.style.top)+b.deltaY+"px";return!1};Toolbox.prototype.wheel=function(a,b){};
